#!/usr/bin/env node

var packager = require('electron-packager')
var package = require('../package.json')
var os = require('os')

var platform = os.platform()
var arch = os.arch()
if (process.argv.indexOf('--all') !== -1) {
  arch = platform = 'all'
}

var opts = {
  dir: '.',
  name: 'Hacker Menu',
  overwrite: true,
  icon: 'images/Icon@1024.icns',
  platform: platform,
  arch: arch,
  out: 'build',
  version: package.config.electron_version,
  ignore: [
    'src',
    'script',
    'build',
    'release',
    'images/(Icon@1024.icns|screenshot.png)',
    'node_modules/(babel|standard|csscomb)',
    'node_modules/electron-(packager|prebuild|rebuild)'
  ]
}
if (!process.env.CI && process.argv.indexOf('--sign') !== -1) {
  opts.sign = 'Developer ID Application: Jingwen Ou'
}
packager(opts, function done (err, appPaths) {
  if (err) {
    if (err.message) {
      console.error(err.message)
    } else {
      console.error(err, err.stack)
    }

    process.exit(1)
  }

  if (appPaths.length > 1) {
    console.error('Wrote new apps to:\n' + appPaths.join('\n'))
  } else if (appPaths.length === 1) {
    console.error('Wrote new app to', appPaths[0])
  }
})
