#!/usr/bin/env node

var packager = require('electron-packager')
var package = require('../package.json')
var os = require('os')
var path = require('path')

if (process.argv[2] === '--all') {
  // Build for all platforms
  var archs = ['ia32', 'x64']
  var platforms = ['linux', 'win32', 'darwin']

  platforms.forEach(function (plat) {
    archs.forEach(function (arch) {
      pack(plat, arch)
    })
  })
} else {
  // Build for current platform only
  pack(os.platform(), os.arch())
}

function pack (plat, arch) {
  // There is no darwin ia32 electron
  if (plat === 'darwin' && arch === 'ia32') return

  var opts = {
    dir: '.',
    name: 'Hacker Menu',
    overwrite: true,
    icon: 'images/Icon@1024.icns',
    platform: plat,
    arch: arch,
    version: package.config.electron_version,
    ignore: [
      'src',
      'script',
      'release',
      'node_modules/(babel|standard|csscomb)',
      'node_modules/electron-(packager|prebuild|rebuild)'
    ]
  }

  if (!process.env.CI) {
    opts.sign = 'Developer ID Application: Jingwen Ou'
  }
  packager(opts, function done (err, appPaths) {
    if (err) {
      if (err.message) {
        console.error(err.message)
      } else {
        console.error(err, err.stack)
      }

      process.exit(1)
    }

    if (appPaths.length > 1) {
      console.error('Wrote new apps to:\n' + appPaths.join('\n'))
    } else if (appPaths.length === 1) {
      console.error('Wrote new app to', appPaths[0])
    }
  })
}
